/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CourseLevel = IDL.Variant({
  'Beginner' : IDL.Null,
  'Advanced' : IDL.Null,
  'Intermediate' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : IDL.Int,
  'durationHours' : IDL.Nat,
  'description' : IDL.Text,
  'level' : CourseLevel,
  'modulesCount' : IDL.Nat,
  'price' : IDL.Nat,
  'videoUrl' : IDL.Text,
});
export const ProgressStatus = IDL.Variant({
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
  'NotStarted' : IDL.Null,
});
export const Enrollment = IDL.Record({
  'progressStatus' : ProgressStatus,
  'studentPrincipal' : IDL.Principal,
  'enrolledAt' : IDL.Int,
  'courseId' : IDL.Nat,
});
export const InstructorProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const RevenueSummary = IDL.Record({
  'totalRevenue' : IDL.Nat,
  'courseTitle' : IDL.Text,
  'courseId' : IDL.Nat,
  'enrollmentCount' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCourse' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        CourseLevel,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [Course],
      [],
    ),
  'createCourseCheckoutSession' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteCourse' : IDL.Func([IDL.Nat], [], []),
  'enrollAfterPayment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getInstructorProfile' : IDL.Func(
      [],
      [IDL.Opt(InstructorProfile)],
      ['query'],
    ),
  'getMyEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'getRevenueSummaries' : IDL.Func([], [IDL.Vec(RevenueSummary)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEnrolledInCourse' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCourse' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        CourseLevel,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateInstructorProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateMyProgressStatus' : IDL.Func([IDL.Nat, ProgressStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CourseLevel = IDL.Variant({
    'Beginner' : IDL.Null,
    'Advanced' : IDL.Null,
    'Intermediate' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : IDL.Int,
    'durationHours' : IDL.Nat,
    'description' : IDL.Text,
    'level' : CourseLevel,
    'modulesCount' : IDL.Nat,
    'price' : IDL.Nat,
    'videoUrl' : IDL.Text,
  });
  const ProgressStatus = IDL.Variant({
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
    'NotStarted' : IDL.Null,
  });
  const Enrollment = IDL.Record({
    'progressStatus' : ProgressStatus,
    'studentPrincipal' : IDL.Principal,
    'enrolledAt' : IDL.Int,
    'courseId' : IDL.Nat,
  });
  const InstructorProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const RevenueSummary = IDL.Record({
    'totalRevenue' : IDL.Nat,
    'courseTitle' : IDL.Text,
    'courseId' : IDL.Nat,
    'enrollmentCount' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCourse' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          CourseLevel,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [Course],
        [],
      ),
    'createCourseCheckoutSession' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteCourse' : IDL.Func([IDL.Nat], [], []),
    'enrollAfterPayment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getInstructorProfile' : IDL.Func(
        [],
        [IDL.Opt(InstructorProfile)],
        ['query'],
      ),
    'getMyEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'getRevenueSummaries' : IDL.Func([], [IDL.Vec(RevenueSummary)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEnrolledInCourse' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCourse' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          CourseLevel,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateInstructorProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateMyProgressStatus' : IDL.Func([IDL.Nat, ProgressStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };