/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'createdAt' : bigint,
  'durationHours' : bigint,
  'description' : string,
  'level' : CourseLevel,
  'modulesCount' : bigint,
  'price' : bigint,
  'videoUrl' : string,
}
export type CourseLevel = { 'Beginner' : null } |
  { 'Advanced' : null } |
  { 'Intermediate' : null };
export interface Enrollment {
  'progressStatus' : ProgressStatus,
  'studentPrincipal' : Principal,
  'enrolledAt' : bigint,
  'courseId' : bigint,
}
export interface InstructorProfile {
  'bio' : string,
  'name' : string,
  'photoUrl' : string,
}
export type ProgressStatus = { 'InProgress' : null } |
  { 'Completed' : null } |
  { 'NotStarted' : null };
export interface RevenueSummary {
  'totalRevenue' : bigint,
  'courseTitle' : string,
  'courseId' : bigint,
  'enrollmentCount' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCourse' : ActorMethod<
    [string, string, bigint, CourseLevel, bigint, bigint, string, string],
    Course
  >,
  'createCourseCheckoutSession' : ActorMethod<[bigint, string, string], string>,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'enrollAfterPayment' : ActorMethod<[bigint, string], undefined>,
  'getAllEnrollments' : ActorMethod<[], Array<Enrollment>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[bigint], [] | [Course]>,
  'getInstructorProfile' : ActorMethod<[], [] | [InstructorProfile]>,
  'getMyEnrollments' : ActorMethod<[], Array<Enrollment>>,
  'getRevenueSummaries' : ActorMethod<[], Array<RevenueSummary>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEnrolledInCourse' : ActorMethod<[bigint], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listCourses' : ActorMethod<[], Array<Course>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCourse' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      CourseLevel,
      bigint,
      bigint,
      string,
      string,
    ],
    undefined
  >,
  'updateInstructorProfile' : ActorMethod<[string, string, string], undefined>,
  'updateMyProgressStatus' : ActorMethod<[bigint, ProgressStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];